// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:658a6642-f0a3-4724-8a26-3106407d543a",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_EW3ePbUiW",
    "aws_user_pools_web_client_id": "5l3htv1mh8q1i50tqnht95q00a",
    "oauth": {}
};


export default awsmobile;
